/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BangunDatar;
import BangunDatar.Lingkaran;
import BangunDatar.PersegiPanjang;

import javax.swing.JFrame;

/**
 *
 * @author Fikri
 */
public class TampilanAwal extends javax.swing.JFrame {

    /**
     * Creates new form TampilanAwal
     */
    public TampilanAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        ApkBangunDatar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ApkBangunDatar1 = new javax.swing.JLabel();
        ApkBangunDatar2 = new javax.swing.JLabel();
        iconLingkaran = new javax.swing.JLabel();
        bglingkaran = new javax.swing.JPanel();
        Lingkaran = new javax.swing.JButton();
        iconpersegi = new javax.swing.JLabel();
        Persegi = new javax.swing.JButton();
        persegi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Segitiga = new javax.swing.JButton();
        iconpersegipanjang = new javax.swing.JLabel();
        PersegiPanjang = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApkBangunDatar.setBackground(new java.awt.Color(255, 255, 255));
        ApkBangunDatar.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 18)); // NOI18N
        ApkBangunDatar.setForeground(new java.awt.Color(255, 255, 255));
        ApkBangunDatar.setText("Pilih bangun datar yang ingin digunakan");
        jPanel3.add(ApkBangunDatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 25));

        jPanel4.setBackground(new java.awt.Color(236, 236, 236));

        ApkBangunDatar1.setBackground(new java.awt.Color(102, 102, 102));
        ApkBangunDatar1.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        ApkBangunDatar1.setText("Aplikasi Bangun Datar");

        ApkBangunDatar2.setBackground(new java.awt.Color(102, 102, 102));
        ApkBangunDatar2.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        ApkBangunDatar2.setText("Aplikasi Bangun Datar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(ApkBangunDatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ApkBangunDatar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApkBangunDatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApkBangunDatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        iconLingkaran.setBackground(new java.awt.Color(255, 255, 255));
        iconLingkaran.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        iconLingkaran.setForeground(new java.awt.Color(255, 255, 255));
        iconLingkaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lingkaran.png"))); // NOI18N
        jPanel3.add(iconLingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, 160));

        bglingkaran.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout bglingkaranLayout = new javax.swing.GroupLayout(bglingkaran);
        bglingkaran.setLayout(bglingkaranLayout);
        bglingkaranLayout.setHorizontalGroup(
            bglingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        bglingkaranLayout.setVerticalGroup(
            bglingkaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel3.add(bglingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        Lingkaran.setText("jButton1");
        Lingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LingkaranActionPerformed(evt);
            }
        });
        jPanel3.add(Lingkaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, 140));

        iconpersegi.setBackground(new java.awt.Color(255, 255, 255));
        iconpersegi.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        iconpersegi.setForeground(new java.awt.Color(255, 255, 255));
        iconpersegi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/persegi.png"))); // NOI18N
        jPanel3.add(iconpersegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 160, 160));

        Persegi.setText("jButton1");
        Persegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersegiActionPerformed(evt);
            }
        });
        jPanel3.add(Persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 140, 140));

        persegi.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        persegi.setForeground(new java.awt.Color(255, 255, 255));
        persegi.setText("Persegi");
        jPanel3.add(persegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lingkaran");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/segitiga.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 160, 160));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 190, 170));

        Segitiga.setText("jButton1");
        Segitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegitigaActionPerformed(evt);
            }
        });
        jPanel3.add(Segitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 170, 150));

        iconpersegipanjang.setBackground(new java.awt.Color(255, 255, 255));
        iconpersegipanjang.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        iconpersegipanjang.setForeground(new java.awt.Color(255, 255, 255));
        iconpersegipanjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/persegi panjang.png"))); // NOI18N
        jPanel3.add(iconpersegipanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 220, 150));

        PersegiPanjang.setText("jButton1");
        PersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersegiPanjangActionPerformed(evt);
            }
        });
        jPanel3.add(PersegiPanjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 200, 130));

        jLabel12.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Persegi Panjang");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel13.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Segitiga");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersegiPanjangActionPerformed
        // TODO add your handling code here:
        PersegiPanjang c = new PersegiPanjang();
        c.setVisible(true);
        c.pack();
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        c.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_PersegiPanjangActionPerformed

    private void LingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LingkaranActionPerformed
        // TODO add your handling code here:
        Lingkaran a = new Lingkaran();
        a.setVisible(true);
        a.pack();
        a.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LingkaranActionPerformed

    private void PersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersegiActionPerformed
        // TODO add your handling code here:
        Persegi b = new Persegi();
        b.setVisible(true);
        b.pack();
        b.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        b.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_PersegiActionPerformed

    private void SegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegitigaActionPerformed
        // TODO add your handling code here:
        Segitiga d = new Segitiga();
        d.setVisible(true);
        d.pack();
        d.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApkBangunDatar;
    private javax.swing.JLabel ApkBangunDatar1;
    private javax.swing.JLabel ApkBangunDatar2;
    private javax.swing.JButton Lingkaran;
    private javax.swing.JButton Persegi;
    private javax.swing.JButton PersegiPanjang;
    private javax.swing.JButton Segitiga;
    private javax.swing.JPanel bglingkaran;
    private javax.swing.JLabel iconLingkaran;
    private javax.swing.JLabel iconpersegi;
    private javax.swing.JLabel iconpersegipanjang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel persegi;
    // End of variables declaration//GEN-END:variables
}
